FROM base-hadoop

MAINTAINER Mitchell Templeton <mitchelltempleton94@gmail.com>

#===============================================
# Entrypoint
#===============================================
COPY entrypoint.sh /
CMD ["/entrypoint.sh"]

